### PR TITLE
Added a handlebars helper to truncate a string

### PR DESCRIPTION
**Pull request by elephantengine**
**FUNCTION**
truncate(str, length)

**DESCRIPTION (WHAT)**
Returns the first X characters in a string (unless it reaches the end 
of the string first, in which case it will return fewer). Returns a 
new string that is truncated to the given length.

**USE CASE (WHY)**
As a merchant, I want to display a card, at the bottom of
my home page that highlights the most recent blog post. In the card,
I want to display the blog thumbnail, title and the first 40 characters
of the post's body. In order to extract the first 40 characters, I need
a Handlebars helper that works like the javascript substring() function. 
 
**USAGE**
{{lang (truncate 'blog.post.body.' 40) }}

@mcampa , @junedkazi , @mjschock

### CODE REVIEW

**Comment by mcampa** [comment]
Looks good to me. Do you mid writing a simple test case in `/tests/helpers`? 
take a look at this example

@bc-mkatz can you add this new helper to the docs?

**Comment by bc-mkatz** [comment]
@mcampa: Looks straightforward, will add this to the docs later today. Thanks.

**Comment by mcampa** [comment]
Awesome, thanks for writing the test. Just one more thing, can you fix the lint errors?

```
/home/travis/build/bigcommerce/paper/test/helpers/truncate.js
  16:7  error  Expected indentation of 8 space characters but found 6  indent
  17:7  error  Expected indentation of 8 space characters but found 6  indent
```

**Comment by mcampa** [comment]
👍

**Pull request merged**
