### PR TITLE
MERC-1025 Expose localeName to the template context

### PR DESCRIPTION
**Pull request by mcampa**
- added tests for the localizer library
- deleted compiler code that is not used
- Exposes localeName to the template context

@lord2800 @mattolson @bc-ong @sherrybc

### CODE REVIEW

**Comment by lord2800** [comment]
Is there a way for the end visitor to override the locale? Browsers are inconsistent at best about sending the right locale headers.

👍 regardless.

**Comment by mcampa** [comment]
Visitors can set the browser to send whatever locale they want, but stapler/paper will only set `localeName` to a value supported by the theme.

**Comment by lord2800** [comment]
Right, but let's say I'm a visitor whose browser is set to en-CA but I want en-US or fr-CA. Can I override the browser's decision without changing the browser somehow?

**Comment by mcampa** [comment]
No, we currently don't do that. But is doable. We could store the preferred language in a cookie for example.

**Pull request merged**
