### PR TITLE
Drop package lock file from the library

### PR DESCRIPTION
**Pull request by junedkazi**
@bigcommerce/storefront-team

### CODE REVIEW

**Comment by MaxGenash** [comment]
@junedkazi just curious, why did we do that (Drop package lock file from the library)?

**Comment by mattolson** [comment]
@MaxGenash In general, it is best for library maintainers to have loose dependencies and leave it up to the application layer to define strict dependencies. This helps avoid conflict between what the library needs and what the application needs (easier to resolve version conflicts between the two). See https://dev.to/gajus/stop-using-package-lock-json-or-yarn-lock-3ddi for some more insight.

**Comment by jairo-bc** [comment]
So we need to add to .gitignore lock files for dependent projects

**Comment by mattolson** [comment]
@jairo-bc Yeah, good idea -- that will help avoid adding that file accidentally in the future

**Pull request merged**
